### ISSUE TITLE
Touchstart and touchend prevent scrolling

### ISSUE THREAD

**Issue by robmausser** [DavidAnson/live-photo-web#2]
The issue on mobile when using live-photo-element is that I have a bunch of "live photos" in a scrolling list.

using touchstart kills the scroll event. 

Is there a way to say "if touchmove, ignore touchstart" and allow for scrolling?

Heres my site to show whats happening.

http://robmausser.com/touchmove/index.php

Trying on Android Chrome browser, I cant scroll, my scrolling events get captured by the touchstart.

Cheers

**Comment by DavidAnson** [comment]
IIRC, start comes before move, so I’m not sure it’ll be as easy as you suggest. However, I’d recommend looking at Apple’s implementation first - I have not used it, but expect they did a better job than my simple experiment. https://developer.apple.com/documentation/livephotoskitjs
